name = "HandIsomorphism"
uuid = "3834e556-cfb7-4bde-bcfd-1d920ea1697f"
version = "0.1.0"
authors = ["Yacine Al-Najjar <yalnajja@gmail.com>"]

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
HandIsomorphism_jll = "0.0.1"
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
HandIsomorphism_jll = "984f9c1f-46fe-5a04-8363-0cf7ea158318"

[targets]
test = ["Test","HandIsomorphism_jll"]
